openapi: 3.0.3
info:
  title: Task Management API
  description: API for managing user tasks with CRUD operations
  version: 1.0.0
  contact:
    name: Todo App Development Team
servers:
  - url: http://localhost:8000/api
    description: Local development server
  - url: https://api.todoapp.com/v1
    description: Production server

paths:
  /{user_id}/tasks:
    get:
      summary: List user tasks
      description: Retrieve all tasks for a specific user with optional filtering and pagination
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: integer
        - name: status
          in: query
          required: false
          description: Filter tasks by completion status
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
        - name: sort
          in: query
          required: false
          description: Field to sort by
          schema:
            type: string
            enum: [created, updated, title]
            default: created
        - name: order
          in: query
          required: false
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: limit
          in: query
          required: false
          description: Maximum number of results to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: offset
          in: query
          required: false
          description: Number of results to skip
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                    description: Total number of tasks matching the query
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      security:
        - bearerAuth: []
    post:
      summary: Create a new task
      description: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      security:
        - bearerAuth: []

  /{user_id}/tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by its ID for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
        - name: id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      security:
        - bearerAuth: []
    put:
      summary: Update a task
      description: Update an entire task with new values
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      security:
        - bearerAuth: []
    delete:
      summary: Delete a task
      description: Permanently delete a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
        - name: id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      security:
        - bearerAuth: []

  /{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion status
      description: Update the completion status of a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: The new completion status
                version:
                  type: integer
                  description: Current version for optimistic locking (optional)
              required:
                - completed
      responses:
        '200':
          description: Task completion status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from authentication endpoint
  responses:
    TooManyRequestsError:
      description: Too many requests - rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the task
          readOnly: true
        title:
          type: string
          description: Title of the task
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Optional description of the task
          maxLength: 1000
        completed:
          type: boolean
          description: Whether the task is completed
          default: false
        user_id:
          type: integer
          description: ID of the user who owns the task
        version:
          type: integer
          description: Version number for optimistic locking
          readOnly: true
        created_at:
          type: string
          format: date-time
          description: When the task was created
          readOnly: true
        updated_at:
          type: string
          format: date-time
          description: When the task was last updated
          readOnly: true
      required:
        - id
        - title
        - completed
        - user_id
        - version
        - created_at
        - updated_at
    TaskCreate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Optional description of the task
          maxLength: 1000
        completed:
          type: boolean
          description: Whether the task is completed
          default: false
      required:
        - title
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: New title of the task
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: New description of the task
          maxLength: 1000
        completed:
          type: boolean
          description: New completion status
        version:
          type: integer
          description: Current version for optimistic locking (optional)
  responses:
    BadRequestError:
      description: Bad request - validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnauthorizedError:
      description: Unauthorized - invalid or expired JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ForbiddenError:
      description: Forbidden - user_id mismatch or insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Not found - requested resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ConflictError:
      description: Conflict - version mismatch during concurrent update
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    TooManyRequestsError:
      description: Too many requests - rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        detail:
          type: object
          properties:
            code:
              type: string
              description: Error code
            message:
              type: string
              description: Human-readable error message
            field:
              type: string
              description: Field related to the error (if applicable)
      required:
        - detail

security:
  - bearerAuth: []